### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by Zohra-Neda** [Zohra-Neda/Portfolio#7]
Link to the online version of my Portfolio app : https://zohra-neda.github.io/Portfolio/

**Comment by LionRouge1** [comment]
Hi @zohra-neda, 

# STATUS: APPROVED! 🥇 💯 
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

![done](https://media.giphy.com/media/a5llhdWKMOIfneMCpB/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
